netwwork:
  dev:

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
    networks:
      - dev

backend:
  build:
    context: ./backend
  networks:
      - dev

frontend:
  build:
    context: ./ui
  networks:
      - dev