version: '3.9'

networks:
  dev:

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ui/dist:/usr/share/nginx/html
    depends_on:
      - backend
    networks:
      - dev